name: audio_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  audio_video_progress_bar: ^1.0.0
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  rxdart: ^0.27.7
  flutter_audio_query: ^0.3.5+6
  flutter_animate: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/json/
